apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-galera
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    chart: mariadb-galera
    targetRevision: 14.0.9
    helm:
      valueFiles:
      - $values/argo-apps/mariadb-galera-values.yaml
  - repoURL: 'https://github.com/andrewp88/argocd.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: galera